### PR TITLE
Create initial timeslots

### PR DESCRIPTION
**Pull request by BrodyGimson**
- Added functionality for selecting random timeslots. Added in tests and a full random assignment test for it too.
- Improved error handling in the functions

**Future To-Do**
- Not going to randomly assign 3 hour lectures, but ones given in the historic data still need to figure out how to handle them
- I tried to make variable and function names self explanatory but I can add more comments if you request before merging with main

### CODE REVIEW

**Comment by BrodyGimson** [comment]
Something not quite right. Moving this to draft

**Comment by BrodyGimson** [comment]
False alarm, test data contained two sections of a course (CSC 111) in fall courses so it showed up twice.

**Review by treavorgagne — APPROVED** [review]
I trust that it works. Test looks good to me.

**Review by treavorgagne — APPROVED** [review]
Both test and logic look good.

**Pull request merged**
